version: '3.8'
services:
  app:
    container_name: 'laravel-devhero-app'
    build:
        context: .
        dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
        - ./app:/var/www
  web:
    container_name: 'laravel-devhero-web'
    build:
        context: .
        dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
        - ./app:/var/www
        - ./docker/upload.ini:/usr/local/etc/php/php.ini
    depends_on:
        - "app"
    ports:
        - 80:80